/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.utilidades;

/**
 *
 * @author campu
 */
public class PanelUser extends javax.swing.JPanel {

    /**
     * Creates new form PanelUser
     */
    public PanelUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        txtUser = new com.bolivia.login.swing.JCTextField();
        btnNext = new com.bolivia.login.swing.JCButton();
        cLabel1 = new com.bolivia.login.swing.CLabel();
        lblError = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(120, 280));
        setPreferredSize(new java.awt.Dimension(358, 319));
        setLayout(new java.awt.GridBagLayout());

        txtUser.setPlaceholder("Introduce tu usuario");
        txtUser.setPreferredSize(new java.awt.Dimension(278, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(28, 40, 7, 40);
        add(txtUser, gridBagConstraints);

        btnNext.setText("Siguiente");
        btnNext.setPreferredSize(new java.awt.Dimension(278, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        add(btnNext, gridBagConstraints);

        cLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ic_people.jpg"))); // NOI18N
        cLabel1.setText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        add(cLabel1, gridBagConstraints);

        lblError.setForeground(new java.awt.Color(221, 75, 57));
        lblError.setText("Error");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        add(lblError, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.bolivia.login.swing.JCButton btnNext;
    private com.bolivia.login.swing.CLabel cLabel1;
    public javax.swing.JLabel lblError;
    public com.bolivia.login.swing.JCTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
